//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MarsAhletic.WebUI.priusWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Prius Web ServiceSoap", Namespace="http://prius.local")]
    public partial class PriusWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCustomerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCenterListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPuchaseServicesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCurrencyRatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback createPurchaseOrderInLogoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PriusWebService() {
            this.Url = global::MarsAhletic.WebUI.Properties.Settings.Default.MarsAhletic_WebUI_priusWebService_Prius_x0020_Web_x0020_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCustomerListCompletedEventHandler getCustomerListCompleted;
        
        /// <remarks/>
        public event getItemListCompletedEventHandler getItemListCompleted;
        
        /// <remarks/>
        public event getCenterListCompletedEventHandler getCenterListCompleted;
        
        /// <remarks/>
        public event getPuchaseServicesListCompletedEventHandler getPuchaseServicesListCompleted;
        
        /// <remarks/>
        public event getCurrencyRatesCompletedEventHandler getCurrencyRatesCompleted;
        
        /// <remarks/>
        public event loginTestCompletedEventHandler loginTestCompleted;
        
        /// <remarks/>
        public event createPurchaseOrderInLogoCompletedEventHandler createPurchaseOrderInLogoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/getCustomerList", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getCustomerList(System.DateTime UpdateDate, string code, string token) {
            object[] results = this.Invoke("getCustomerList", new object[] {
                        UpdateDate,
                        code,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerListAsync(System.DateTime UpdateDate, string code, string token) {
            this.getCustomerListAsync(UpdateDate, code, token, null);
        }
        
        /// <remarks/>
        public void getCustomerListAsync(System.DateTime UpdateDate, string code, string token, object userState) {
            if ((this.getCustomerListOperationCompleted == null)) {
                this.getCustomerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerListOperationCompleted);
            }
            this.InvokeAsync("getCustomerList", new object[] {
                        UpdateDate,
                        code,
                        token}, this.getCustomerListOperationCompleted, userState);
        }
        
        private void OngetCustomerListOperationCompleted(object arg) {
            if ((this.getCustomerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerListCompleted(this, new getCustomerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/getItemList", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getItemList(System.DateTime UpdateDate, string code, string token) {
            object[] results = this.Invoke("getItemList", new object[] {
                        UpdateDate,
                        code,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getItemListAsync(System.DateTime UpdateDate, string code, string token) {
            this.getItemListAsync(UpdateDate, code, token, null);
        }
        
        /// <remarks/>
        public void getItemListAsync(System.DateTime UpdateDate, string code, string token, object userState) {
            if ((this.getItemListOperationCompleted == null)) {
                this.getItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetItemListOperationCompleted);
            }
            this.InvokeAsync("getItemList", new object[] {
                        UpdateDate,
                        code,
                        token}, this.getItemListOperationCompleted, userState);
        }
        
        private void OngetItemListOperationCompleted(object arg) {
            if ((this.getItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getItemListCompleted(this, new getItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/getCenterList", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getCenterList(System.DateTime UpdateDate, string code, string token) {
            object[] results = this.Invoke("getCenterList", new object[] {
                        UpdateDate,
                        code,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getCenterListAsync(System.DateTime UpdateDate, string code, string token) {
            this.getCenterListAsync(UpdateDate, code, token, null);
        }
        
        /// <remarks/>
        public void getCenterListAsync(System.DateTime UpdateDate, string code, string token, object userState) {
            if ((this.getCenterListOperationCompleted == null)) {
                this.getCenterListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCenterListOperationCompleted);
            }
            this.InvokeAsync("getCenterList", new object[] {
                        UpdateDate,
                        code,
                        token}, this.getCenterListOperationCompleted, userState);
        }
        
        private void OngetCenterListOperationCompleted(object arg) {
            if ((this.getCenterListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCenterListCompleted(this, new getCenterListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/getPuchaseServicesList", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getPuchaseServicesList(System.DateTime UpdateDate, string code, string token) {
            object[] results = this.Invoke("getPuchaseServicesList", new object[] {
                        UpdateDate,
                        code,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getPuchaseServicesListAsync(System.DateTime UpdateDate, string code, string token) {
            this.getPuchaseServicesListAsync(UpdateDate, code, token, null);
        }
        
        /// <remarks/>
        public void getPuchaseServicesListAsync(System.DateTime UpdateDate, string code, string token, object userState) {
            if ((this.getPuchaseServicesListOperationCompleted == null)) {
                this.getPuchaseServicesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPuchaseServicesListOperationCompleted);
            }
            this.InvokeAsync("getPuchaseServicesList", new object[] {
                        UpdateDate,
                        code,
                        token}, this.getPuchaseServicesListOperationCompleted, userState);
        }
        
        private void OngetPuchaseServicesListOperationCompleted(object arg) {
            if ((this.getPuchaseServicesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPuchaseServicesListCompleted(this, new getPuchaseServicesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/getCurrencyRates", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getCurrencyRates(System.DateTime currencyDate, string curCode, string token) {
            object[] results = this.Invoke("getCurrencyRates", new object[] {
                        currencyDate,
                        curCode,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getCurrencyRatesAsync(System.DateTime currencyDate, string curCode, string token) {
            this.getCurrencyRatesAsync(currencyDate, curCode, token, null);
        }
        
        /// <remarks/>
        public void getCurrencyRatesAsync(System.DateTime currencyDate, string curCode, string token, object userState) {
            if ((this.getCurrencyRatesOperationCompleted == null)) {
                this.getCurrencyRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCurrencyRatesOperationCompleted);
            }
            this.InvokeAsync("getCurrencyRates", new object[] {
                        currencyDate,
                        curCode,
                        token}, this.getCurrencyRatesOperationCompleted, userState);
        }
        
        private void OngetCurrencyRatesOperationCompleted(object arg) {
            if ((this.getCurrencyRatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCurrencyRatesCompleted(this, new getCurrencyRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/loginTest", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string loginTest(string logoUserName, string logoPassword, string logoFrmNr, string logoFrmPeriod, string token) {
            object[] results = this.Invoke("loginTest", new object[] {
                        logoUserName,
                        logoPassword,
                        logoFrmNr,
                        logoFrmPeriod,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginTestAsync(string logoUserName, string logoPassword, string logoFrmNr, string logoFrmPeriod, string token) {
            this.loginTestAsync(logoUserName, logoPassword, logoFrmNr, logoFrmPeriod, token, null);
        }
        
        /// <remarks/>
        public void loginTestAsync(string logoUserName, string logoPassword, string logoFrmNr, string logoFrmPeriod, string token, object userState) {
            if ((this.loginTestOperationCompleted == null)) {
                this.loginTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginTestOperationCompleted);
            }
            this.InvokeAsync("loginTest", new object[] {
                        logoUserName,
                        logoPassword,
                        logoFrmNr,
                        logoFrmPeriod,
                        token}, this.loginTestOperationCompleted, userState);
        }
        
        private void OnloginTestOperationCompleted(object arg) {
            if ((this.loginTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginTestCompleted(this, new loginTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://prius.local/createPurchaseOrderInLogo", RequestNamespace="http://prius.local", ResponseNamespace="http://prius.local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT[] createPurchaseOrderInLogo(PURCHASE_ORDER[] orderList, string token) {
            object[] results = this.Invoke("createPurchaseOrderInLogo", new object[] {
                        orderList,
                        token});
            return ((RESULT[])(results[0]));
        }
        
        /// <remarks/>
        public void createPurchaseOrderInLogoAsync(PURCHASE_ORDER[] orderList, string token) {
            this.createPurchaseOrderInLogoAsync(orderList, token, null);
        }
        
        /// <remarks/>
        public void createPurchaseOrderInLogoAsync(PURCHASE_ORDER[] orderList, string token, object userState) {
            if ((this.createPurchaseOrderInLogoOperationCompleted == null)) {
                this.createPurchaseOrderInLogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreatePurchaseOrderInLogoOperationCompleted);
            }
            this.InvokeAsync("createPurchaseOrderInLogo", new object[] {
                        orderList,
                        token}, this.createPurchaseOrderInLogoOperationCompleted, userState);
        }
        
        private void OncreatePurchaseOrderInLogoOperationCompleted(object arg) {
            if ((this.createPurchaseOrderInLogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createPurchaseOrderInLogoCompleted(this, new createPurchaseOrderInLogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prius.local")]
    public partial class PURCHASE_ORDER {
        
        private string cLIENT_INTERNAL_NUMBERField;
        
        private string nUMBERField;
        
        private string dOC_TRACK_NRField;
        
        private System.DateTime dATEField;
        
        private string tIMEField;
        
        private string dOC_NUMBERField;
        
        private string aUXIL_CODEField;
        
        private string aUTH_CODEField;
        
        private string aRP_CODEField;
        
        private string aRP_CODE_SHPMField;
        
        private string sHIPLOC_CODEField;
        
        private string gL_CODEField;
        
        private string sOURCE_WHField;
        
        private string sOURCE_COST_GRPField;
        
        private double aDD_DISCOUNTSField;
        
        private double tOTAL_DISCOUNTSField;
        
        private double tOTAL_DISCOUNTEDField;
        
        private double tOTAL_VATField;
        
        private double tOTAL_GROSSField;
        
        private double tOTAL_NETField;
        
        private double rC_RATEField;
        
        private double rC_NETField;
        
        private string cURRSEL_TOTALField;
        
        private string nOTES1Field;
        
        private string nOTES2Field;
        
        private string nOTES3Field;
        
        private string nOTES4Field;
        
        private string pAYMENT_CODEField;
        
        private string dIVISIONField;
        
        private string dEPARTMENTField;
        
        private string oRDER_STATUSField;
        
        private string sALESMAN_CODEField;
        
        private string sHIPMENT_TYPEField;
        
        private string sHIPPING_AGENTField;
        
        private string cURRSEL_DETAILSField;
        
        private string tRADING_GRPField;
        
        private int dATA_REFERENCEField;
        
        private string fACTORYField;
        
        private string iTEXTField;
        
        private string cUST_ORD_NOField;
        
        private string dOC_TRACKING_NRField;
        
        private string cURR_TRANSACTINField;
        
        private string pROJECT_CODEField;
        
        private string aFFECT_RISKField;
        
        private string gUIDField;
        
        private double tC_RATEField;
        
        private double tC_NETField;
        
        private double eXCHINFO_ADD_DISCOUNTSField;
        
        private double eXCHINFO_TOTAL_DISCOUNTSField;
        
        private double eXCHINFO_TOTAL_DISCOUNTEDField;
        
        private double eXCHINFO_TOTAL_VATField;
        
        private double eXCHINFO_GROSS_TOTALField;
        
        private string wITH_PAYMENTField;
        
        private bool cREATE_INVOICEField;
        
        private TRANSACTIONS_PURCHASE_ORDER[] tRANSACTIONS_Field;
        
        private PAYMENT_LIST_PURCHASE_ORDER[] pAYMENT_LIST_Field;
        
        /// <remarks/>
        public string CLIENT_INTERNAL_NUMBER {
            get {
                return this.cLIENT_INTERNAL_NUMBERField;
            }
            set {
                this.cLIENT_INTERNAL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string DOC_TRACK_NR {
            get {
                return this.dOC_TRACK_NRField;
            }
            set {
                this.dOC_TRACK_NRField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
            }
        }
        
        /// <remarks/>
        public string TIME {
            get {
                return this.tIMEField;
            }
            set {
                this.tIMEField = value;
            }
        }
        
        /// <remarks/>
        public string DOC_NUMBER {
            get {
                return this.dOC_NUMBERField;
            }
            set {
                this.dOC_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string AUXIL_CODE {
            get {
                return this.aUXIL_CODEField;
            }
            set {
                this.aUXIL_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string AUTH_CODE {
            get {
                return this.aUTH_CODEField;
            }
            set {
                this.aUTH_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string ARP_CODE {
            get {
                return this.aRP_CODEField;
            }
            set {
                this.aRP_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string ARP_CODE_SHPM {
            get {
                return this.aRP_CODE_SHPMField;
            }
            set {
                this.aRP_CODE_SHPMField = value;
            }
        }
        
        /// <remarks/>
        public string SHIPLOC_CODE {
            get {
                return this.sHIPLOC_CODEField;
            }
            set {
                this.sHIPLOC_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string GL_CODE {
            get {
                return this.gL_CODEField;
            }
            set {
                this.gL_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_WH {
            get {
                return this.sOURCE_WHField;
            }
            set {
                this.sOURCE_WHField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_COST_GRP {
            get {
                return this.sOURCE_COST_GRPField;
            }
            set {
                this.sOURCE_COST_GRPField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_DISCOUNTS {
            get {
                return this.aDD_DISCOUNTSField;
            }
            set {
                this.aDD_DISCOUNTSField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL_DISCOUNTS {
            get {
                return this.tOTAL_DISCOUNTSField;
            }
            set {
                this.tOTAL_DISCOUNTSField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL_DISCOUNTED {
            get {
                return this.tOTAL_DISCOUNTEDField;
            }
            set {
                this.tOTAL_DISCOUNTEDField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL_VAT {
            get {
                return this.tOTAL_VATField;
            }
            set {
                this.tOTAL_VATField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL_GROSS {
            get {
                return this.tOTAL_GROSSField;
            }
            set {
                this.tOTAL_GROSSField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL_NET {
            get {
                return this.tOTAL_NETField;
            }
            set {
                this.tOTAL_NETField = value;
            }
        }
        
        /// <remarks/>
        public double RC_RATE {
            get {
                return this.rC_RATEField;
            }
            set {
                this.rC_RATEField = value;
            }
        }
        
        /// <remarks/>
        public double RC_NET {
            get {
                return this.rC_NETField;
            }
            set {
                this.rC_NETField = value;
            }
        }
        
        /// <remarks/>
        public string CURRSEL_TOTAL {
            get {
                return this.cURRSEL_TOTALField;
            }
            set {
                this.cURRSEL_TOTALField = value;
            }
        }
        
        /// <remarks/>
        public string NOTES1 {
            get {
                return this.nOTES1Field;
            }
            set {
                this.nOTES1Field = value;
            }
        }
        
        /// <remarks/>
        public string NOTES2 {
            get {
                return this.nOTES2Field;
            }
            set {
                this.nOTES2Field = value;
            }
        }
        
        /// <remarks/>
        public string NOTES3 {
            get {
                return this.nOTES3Field;
            }
            set {
                this.nOTES3Field = value;
            }
        }
        
        /// <remarks/>
        public string NOTES4 {
            get {
                return this.nOTES4Field;
            }
            set {
                this.nOTES4Field = value;
            }
        }
        
        /// <remarks/>
        public string PAYMENT_CODE {
            get {
                return this.pAYMENT_CODEField;
            }
            set {
                this.pAYMENT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
        
        /// <remarks/>
        public string ORDER_STATUS {
            get {
                return this.oRDER_STATUSField;
            }
            set {
                this.oRDER_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public string SALESMAN_CODE {
            get {
                return this.sALESMAN_CODEField;
            }
            set {
                this.sALESMAN_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string SHIPMENT_TYPE {
            get {
                return this.sHIPMENT_TYPEField;
            }
            set {
                this.sHIPMENT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string SHIPPING_AGENT {
            get {
                return this.sHIPPING_AGENTField;
            }
            set {
                this.sHIPPING_AGENTField = value;
            }
        }
        
        /// <remarks/>
        public string CURRSEL_DETAILS {
            get {
                return this.cURRSEL_DETAILSField;
            }
            set {
                this.cURRSEL_DETAILSField = value;
            }
        }
        
        /// <remarks/>
        public string TRADING_GRP {
            get {
                return this.tRADING_GRPField;
            }
            set {
                this.tRADING_GRPField = value;
            }
        }
        
        /// <remarks/>
        public int DATA_REFERENCE {
            get {
                return this.dATA_REFERENCEField;
            }
            set {
                this.dATA_REFERENCEField = value;
            }
        }
        
        /// <remarks/>
        public string FACTORY {
            get {
                return this.fACTORYField;
            }
            set {
                this.fACTORYField = value;
            }
        }
        
        /// <remarks/>
        public string ITEXT {
            get {
                return this.iTEXTField;
            }
            set {
                this.iTEXTField = value;
            }
        }
        
        /// <remarks/>
        public string CUST_ORD_NO {
            get {
                return this.cUST_ORD_NOField;
            }
            set {
                this.cUST_ORD_NOField = value;
            }
        }
        
        /// <remarks/>
        public string DOC_TRACKING_NR {
            get {
                return this.dOC_TRACKING_NRField;
            }
            set {
                this.dOC_TRACKING_NRField = value;
            }
        }
        
        /// <remarks/>
        public string CURR_TRANSACTIN {
            get {
                return this.cURR_TRANSACTINField;
            }
            set {
                this.cURR_TRANSACTINField = value;
            }
        }
        
        /// <remarks/>
        public string PROJECT_CODE {
            get {
                return this.pROJECT_CODEField;
            }
            set {
                this.pROJECT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string AFFECT_RISK {
            get {
                return this.aFFECT_RISKField;
            }
            set {
                this.aFFECT_RISKField = value;
            }
        }
        
        /// <remarks/>
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        public double TC_RATE {
            get {
                return this.tC_RATEField;
            }
            set {
                this.tC_RATEField = value;
            }
        }
        
        /// <remarks/>
        public double TC_NET {
            get {
                return this.tC_NETField;
            }
            set {
                this.tC_NETField = value;
            }
        }
        
        /// <remarks/>
        public double EXCHINFO_ADD_DISCOUNTS {
            get {
                return this.eXCHINFO_ADD_DISCOUNTSField;
            }
            set {
                this.eXCHINFO_ADD_DISCOUNTSField = value;
            }
        }
        
        /// <remarks/>
        public double EXCHINFO_TOTAL_DISCOUNTS {
            get {
                return this.eXCHINFO_TOTAL_DISCOUNTSField;
            }
            set {
                this.eXCHINFO_TOTAL_DISCOUNTSField = value;
            }
        }
        
        /// <remarks/>
        public double EXCHINFO_TOTAL_DISCOUNTED {
            get {
                return this.eXCHINFO_TOTAL_DISCOUNTEDField;
            }
            set {
                this.eXCHINFO_TOTAL_DISCOUNTEDField = value;
            }
        }
        
        /// <remarks/>
        public double EXCHINFO_TOTAL_VAT {
            get {
                return this.eXCHINFO_TOTAL_VATField;
            }
            set {
                this.eXCHINFO_TOTAL_VATField = value;
            }
        }
        
        /// <remarks/>
        public double EXCHINFO_GROSS_TOTAL {
            get {
                return this.eXCHINFO_GROSS_TOTALField;
            }
            set {
                this.eXCHINFO_GROSS_TOTALField = value;
            }
        }
        
        /// <remarks/>
        public string WITH_PAYMENT {
            get {
                return this.wITH_PAYMENTField;
            }
            set {
                this.wITH_PAYMENTField = value;
            }
        }
        
        /// <remarks/>
        public bool CREATE_INVOICE {
            get {
                return this.cREATE_INVOICEField;
            }
            set {
                this.cREATE_INVOICEField = value;
            }
        }
        
        /// <remarks/>
        public TRANSACTIONS_PURCHASE_ORDER[] TRANSACTIONS_ {
            get {
                return this.tRANSACTIONS_Field;
            }
            set {
                this.tRANSACTIONS_Field = value;
            }
        }
        
        /// <remarks/>
        public PAYMENT_LIST_PURCHASE_ORDER[] PAYMENT_LIST_ {
            get {
                return this.pAYMENT_LIST_Field;
            }
            set {
                this.pAYMENT_LIST_Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PURCHASE_ORDER")]
    public partial class TRANSACTIONS_PURCHASE_ORDER {
        
        private string _ADD_TAX_CODEField;
        
        private double _ADD_TAX_RATEField;
        
        private double _ADD_TAX_CONVFACTField;
        
        private double _ADD_TAX_AMOUNTField;
        
        private double _ADD_TAX_VAT_MATRAHField;
        
        private double _ADD_TAX_DISC_AMOUNTField;
        
        private double _ADD_TAX_AMNTISUPDField;
        
        private double _ADD_TAX_EFFECT_KDVField;
        
        private string tYPEField;
        
        private string mASTER_CODEField;
        
        private string gL_CODE1Field;
        
        private string gL_CODE2Field;
        
        private string oHP_CODE1Field;
        
        private string oHP_CODE2Field;
        
        private string dELVRY_CODEField;
        
        private string aUXIL_CODEField;
        
        private double qUANTITYField;
        
        private double pRICEField;
        
        private double tOTALField;
        
        private string dETAIL_LEVELField;
        
        private string cALC_TYPEField;
        
        private double dISCOUNT_RATEField;
        
        private double cOST_DISTRField;
        
        private double dISCOUNT_DISTRField;
        
        private double vAT_RATEField;
        
        private double vAT_AMOUNTField;
        
        private double vAT_BASEField;
        
        private string uNIT_CODEField;
        
        private string uNIT_CONV1Field;
        
        private string uNIT_CONV2Field;
        
        private System.DateTime dUE_DATEField;
        
        private double rC_XRATEField;
        
        private string sOURCE_WHField;
        
        private string sOURCE_COST_GRPField;
        
        private string dIVISIONField;
        
        private string dEPARTMENTField;
        
        private double tOTAL_NETField;
        
        private int dATA_REFERENCEField;
        
        private string sALESMAN_CODEField;
        
        private string fACTORYField;
        
        private string pROJECT_CODEField;
        
        private string cURR_TRANSACTINField;
        
        private double eXCLINE_PRICEField;
        
        private double eXCLINE_TOTALField;
        
        private double eXCLINE_DIST_COSTField;
        
        private double eXCLINE_DIST_DISCField;
        
        private double eXCLINE_VAT_AMOUNTField;
        
        private double eXCLINE_VAT_MATRAHField;
        
        private double eXCLINE_LINE_NETField;
        
        private double eDT_PRICEField;
        
        private double eDT_CURRField;
        
        private System.DateTime oRG_DUE_DATEField;
        
        private double oRG_QUANTITYField;
        
        private double oRG_PRICEField;
        
        private string aUXIL_CODE2Field;
        
        private double pC_PRICEField;
        
        private int vAT_INCLUDEDField;
        
        private int dEDUCTION_PART1Field;
        
        private int dEDUCTION_PART2Field;
        
        private string tRANS_DESCRIPTIONField;
        
        private string cURR_PRICEField;
        
        private double pR_RATEField;
        
        private string aDD_TAX_CODEField;
        
        private double aDD_TAX_RATEField;
        
        private double aDD_TAX_CONVFACTField;
        
        private double aDD_TAX_AMOUNTField;
        
        private double aDD_TAX_VAT_MATRAHField;
        
        private double aDD_TAX_DISC_AMOUNTField;
        
        private double aDD_TAX_AMNTISUPDField;
        
        private double aDD_TAX_EFFECT_KDVField;
        
        /// <remarks/>
        public string _ADD_TAX_CODE {
            get {
                return this._ADD_TAX_CODEField;
            }
            set {
                this._ADD_TAX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_RATE {
            get {
                return this._ADD_TAX_RATEField;
            }
            set {
                this._ADD_TAX_RATEField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_CONVFACT {
            get {
                return this._ADD_TAX_CONVFACTField;
            }
            set {
                this._ADD_TAX_CONVFACTField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_AMOUNT {
            get {
                return this._ADD_TAX_AMOUNTField;
            }
            set {
                this._ADD_TAX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_VAT_MATRAH {
            get {
                return this._ADD_TAX_VAT_MATRAHField;
            }
            set {
                this._ADD_TAX_VAT_MATRAHField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_DISC_AMOUNT {
            get {
                return this._ADD_TAX_DISC_AMOUNTField;
            }
            set {
                this._ADD_TAX_DISC_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_AMNTISUPD {
            get {
                return this._ADD_TAX_AMNTISUPDField;
            }
            set {
                this._ADD_TAX_AMNTISUPDField = value;
            }
        }
        
        /// <remarks/>
        public double _ADD_TAX_EFFECT_KDV {
            get {
                return this._ADD_TAX_EFFECT_KDVField;
            }
            set {
                this._ADD_TAX_EFFECT_KDVField = value;
            }
        }
        
        /// <remarks/>
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        public string MASTER_CODE {
            get {
                return this.mASTER_CODEField;
            }
            set {
                this.mASTER_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string GL_CODE1 {
            get {
                return this.gL_CODE1Field;
            }
            set {
                this.gL_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        public string GL_CODE2 {
            get {
                return this.gL_CODE2Field;
            }
            set {
                this.gL_CODE2Field = value;
            }
        }
        
        /// <remarks/>
        public string OHP_CODE1 {
            get {
                return this.oHP_CODE1Field;
            }
            set {
                this.oHP_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        public string OHP_CODE2 {
            get {
                return this.oHP_CODE2Field;
            }
            set {
                this.oHP_CODE2Field = value;
            }
        }
        
        /// <remarks/>
        public string DELVRY_CODE {
            get {
                return this.dELVRY_CODEField;
            }
            set {
                this.dELVRY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string AUXIL_CODE {
            get {
                return this.aUXIL_CODEField;
            }
            set {
                this.aUXIL_CODEField = value;
            }
        }
        
        /// <remarks/>
        public double QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        public double PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        public string DETAIL_LEVEL {
            get {
                return this.dETAIL_LEVELField;
            }
            set {
                this.dETAIL_LEVELField = value;
            }
        }
        
        /// <remarks/>
        public string CALC_TYPE {
            get {
                return this.cALC_TYPEField;
            }
            set {
                this.cALC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public double DISCOUNT_RATE {
            get {
                return this.dISCOUNT_RATEField;
            }
            set {
                this.dISCOUNT_RATEField = value;
            }
        }
        
        /// <remarks/>
        public double COST_DISTR {
            get {
                return this.cOST_DISTRField;
            }
            set {
                this.cOST_DISTRField = value;
            }
        }
        
        /// <remarks/>
        public double DISCOUNT_DISTR {
            get {
                return this.dISCOUNT_DISTRField;
            }
            set {
                this.dISCOUNT_DISTRField = value;
            }
        }
        
        /// <remarks/>
        public double VAT_RATE {
            get {
                return this.vAT_RATEField;
            }
            set {
                this.vAT_RATEField = value;
            }
        }
        
        /// <remarks/>
        public double VAT_AMOUNT {
            get {
                return this.vAT_AMOUNTField;
            }
            set {
                this.vAT_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double VAT_BASE {
            get {
                return this.vAT_BASEField;
            }
            set {
                this.vAT_BASEField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT_CODE {
            get {
                return this.uNIT_CODEField;
            }
            set {
                this.uNIT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT_CONV1 {
            get {
                return this.uNIT_CONV1Field;
            }
            set {
                this.uNIT_CONV1Field = value;
            }
        }
        
        /// <remarks/>
        public string UNIT_CONV2 {
            get {
                return this.uNIT_CONV2Field;
            }
            set {
                this.uNIT_CONV2Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DUE_DATE {
            get {
                return this.dUE_DATEField;
            }
            set {
                this.dUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public double RC_XRATE {
            get {
                return this.rC_XRATEField;
            }
            set {
                this.rC_XRATEField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_WH {
            get {
                return this.sOURCE_WHField;
            }
            set {
                this.sOURCE_WHField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_COST_GRP {
            get {
                return this.sOURCE_COST_GRPField;
            }
            set {
                this.sOURCE_COST_GRPField = value;
            }
        }
        
        /// <remarks/>
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL_NET {
            get {
                return this.tOTAL_NETField;
            }
            set {
                this.tOTAL_NETField = value;
            }
        }
        
        /// <remarks/>
        public int DATA_REFERENCE {
            get {
                return this.dATA_REFERENCEField;
            }
            set {
                this.dATA_REFERENCEField = value;
            }
        }
        
        /// <remarks/>
        public string SALESMAN_CODE {
            get {
                return this.sALESMAN_CODEField;
            }
            set {
                this.sALESMAN_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string FACTORY {
            get {
                return this.fACTORYField;
            }
            set {
                this.fACTORYField = value;
            }
        }
        
        /// <remarks/>
        public string PROJECT_CODE {
            get {
                return this.pROJECT_CODEField;
            }
            set {
                this.pROJECT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string CURR_TRANSACTIN {
            get {
                return this.cURR_TRANSACTINField;
            }
            set {
                this.cURR_TRANSACTINField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_PRICE {
            get {
                return this.eXCLINE_PRICEField;
            }
            set {
                this.eXCLINE_PRICEField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_TOTAL {
            get {
                return this.eXCLINE_TOTALField;
            }
            set {
                this.eXCLINE_TOTALField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_DIST_COST {
            get {
                return this.eXCLINE_DIST_COSTField;
            }
            set {
                this.eXCLINE_DIST_COSTField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_DIST_DISC {
            get {
                return this.eXCLINE_DIST_DISCField;
            }
            set {
                this.eXCLINE_DIST_DISCField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_VAT_AMOUNT {
            get {
                return this.eXCLINE_VAT_AMOUNTField;
            }
            set {
                this.eXCLINE_VAT_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_VAT_MATRAH {
            get {
                return this.eXCLINE_VAT_MATRAHField;
            }
            set {
                this.eXCLINE_VAT_MATRAHField = value;
            }
        }
        
        /// <remarks/>
        public double EXCLINE_LINE_NET {
            get {
                return this.eXCLINE_LINE_NETField;
            }
            set {
                this.eXCLINE_LINE_NETField = value;
            }
        }
        
        /// <remarks/>
        public double EDT_PRICE {
            get {
                return this.eDT_PRICEField;
            }
            set {
                this.eDT_PRICEField = value;
            }
        }
        
        /// <remarks/>
        public double EDT_CURR {
            get {
                return this.eDT_CURRField;
            }
            set {
                this.eDT_CURRField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ORG_DUE_DATE {
            get {
                return this.oRG_DUE_DATEField;
            }
            set {
                this.oRG_DUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public double ORG_QUANTITY {
            get {
                return this.oRG_QUANTITYField;
            }
            set {
                this.oRG_QUANTITYField = value;
            }
        }
        
        /// <remarks/>
        public double ORG_PRICE {
            get {
                return this.oRG_PRICEField;
            }
            set {
                this.oRG_PRICEField = value;
            }
        }
        
        /// <remarks/>
        public string AUXIL_CODE2 {
            get {
                return this.aUXIL_CODE2Field;
            }
            set {
                this.aUXIL_CODE2Field = value;
            }
        }
        
        /// <remarks/>
        public double PC_PRICE {
            get {
                return this.pC_PRICEField;
            }
            set {
                this.pC_PRICEField = value;
            }
        }
        
        /// <remarks/>
        public int VAT_INCLUDED {
            get {
                return this.vAT_INCLUDEDField;
            }
            set {
                this.vAT_INCLUDEDField = value;
            }
        }
        
        /// <remarks/>
        public int DEDUCTION_PART1 {
            get {
                return this.dEDUCTION_PART1Field;
            }
            set {
                this.dEDUCTION_PART1Field = value;
            }
        }
        
        /// <remarks/>
        public int DEDUCTION_PART2 {
            get {
                return this.dEDUCTION_PART2Field;
            }
            set {
                this.dEDUCTION_PART2Field = value;
            }
        }
        
        /// <remarks/>
        public string TRANS_DESCRIPTION {
            get {
                return this.tRANS_DESCRIPTIONField;
            }
            set {
                this.tRANS_DESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string CURR_PRICE {
            get {
                return this.cURR_PRICEField;
            }
            set {
                this.cURR_PRICEField = value;
            }
        }
        
        /// <remarks/>
        public double PR_RATE {
            get {
                return this.pR_RATEField;
            }
            set {
                this.pR_RATEField = value;
            }
        }
        
        /// <remarks/>
        public string ADD_TAX_CODE {
            get {
                return this.aDD_TAX_CODEField;
            }
            set {
                this.aDD_TAX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_RATE {
            get {
                return this.aDD_TAX_RATEField;
            }
            set {
                this.aDD_TAX_RATEField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_CONVFACT {
            get {
                return this.aDD_TAX_CONVFACTField;
            }
            set {
                this.aDD_TAX_CONVFACTField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_AMOUNT {
            get {
                return this.aDD_TAX_AMOUNTField;
            }
            set {
                this.aDD_TAX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_VAT_MATRAH {
            get {
                return this.aDD_TAX_VAT_MATRAHField;
            }
            set {
                this.aDD_TAX_VAT_MATRAHField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_DISC_AMOUNT {
            get {
                return this.aDD_TAX_DISC_AMOUNTField;
            }
            set {
                this.aDD_TAX_DISC_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_AMNTISUPD {
            get {
                return this.aDD_TAX_AMNTISUPDField;
            }
            set {
                this.aDD_TAX_AMNTISUPDField = value;
            }
        }
        
        /// <remarks/>
        public double ADD_TAX_EFFECT_KDV {
            get {
                return this.aDD_TAX_EFFECT_KDVField;
            }
            set {
                this.aDD_TAX_EFFECT_KDVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://prius.local")]
    public partial class RESULT {
        
        private string lOGO_FICHE_NUMBERField;
        
        private string cLIENT_INTERNAL_NUMBERField;
        
        private int lOGO_REFERENCEField;
        
        private int lOGO_FIRM_NUMBERField;
        
        private int lOGO_FIRM_PERIODField;
        
        private string rESULT_STRINGField;
        
        private string rESULT_XMLField;
        
        private bool iS_SUCCESSField;
        
        private string lOGO_RECORD_GUIDField;
        
        /// <remarks/>
        public string LOGO_FICHE_NUMBER {
            get {
                return this.lOGO_FICHE_NUMBERField;
            }
            set {
                this.lOGO_FICHE_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_INTERNAL_NUMBER {
            get {
                return this.cLIENT_INTERNAL_NUMBERField;
            }
            set {
                this.cLIENT_INTERNAL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public int LOGO_REFERENCE {
            get {
                return this.lOGO_REFERENCEField;
            }
            set {
                this.lOGO_REFERENCEField = value;
            }
        }
        
        /// <remarks/>
        public int LOGO_FIRM_NUMBER {
            get {
                return this.lOGO_FIRM_NUMBERField;
            }
            set {
                this.lOGO_FIRM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public int LOGO_FIRM_PERIOD {
            get {
                return this.lOGO_FIRM_PERIODField;
            }
            set {
                this.lOGO_FIRM_PERIODField = value;
            }
        }
        
        /// <remarks/>
        public string RESULT_STRING {
            get {
                return this.rESULT_STRINGField;
            }
            set {
                this.rESULT_STRINGField = value;
            }
        }
        
        /// <remarks/>
        public string RESULT_XML {
            get {
                return this.rESULT_XMLField;
            }
            set {
                this.rESULT_XMLField = value;
            }
        }
        
        /// <remarks/>
        public bool IS_SUCCESS {
            get {
                return this.iS_SUCCESSField;
            }
            set {
                this.iS_SUCCESSField = value;
            }
        }
        
        /// <remarks/>
        public string LOGO_RECORD_GUID {
            get {
                return this.lOGO_RECORD_GUIDField;
            }
            set {
                this.lOGO_RECORD_GUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PURCHASE_ORDER")]
    public partial class PAYMENT_LIST_PURCHASE_ORDER {
        
        private System.DateTime dATEField;
        
        private string mODULENRField;
        
        private string tRCODEField;
        
        private double tOTALField;
        
        private System.DateTime pROCDATEField;
        
        private double rEPORTRATEField;
        
        private int dATA_REFERENCEField;
        
        private System.DateTime dISCOUNT_DUEDATEField;
        
        private string pAY_NOField;
        
        private string oP_STATUSField;
        
        private string sIGNField;
        
        /// <remarks/>
        public System.DateTime DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
            }
        }
        
        /// <remarks/>
        public string MODULENR {
            get {
                return this.mODULENRField;
            }
            set {
                this.mODULENRField = value;
            }
        }
        
        /// <remarks/>
        public string TRCODE {
            get {
                return this.tRCODEField;
            }
            set {
                this.tRCODEField = value;
            }
        }
        
        /// <remarks/>
        public double TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PROCDATE {
            get {
                return this.pROCDATEField;
            }
            set {
                this.pROCDATEField = value;
            }
        }
        
        /// <remarks/>
        public double REPORTRATE {
            get {
                return this.rEPORTRATEField;
            }
            set {
                this.rEPORTRATEField = value;
            }
        }
        
        /// <remarks/>
        public int DATA_REFERENCE {
            get {
                return this.dATA_REFERENCEField;
            }
            set {
                this.dATA_REFERENCEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DISCOUNT_DUEDATE {
            get {
                return this.dISCOUNT_DUEDATEField;
            }
            set {
                this.dISCOUNT_DUEDATEField = value;
            }
        }
        
        /// <remarks/>
        public string PAY_NO {
            get {
                return this.pAY_NOField;
            }
            set {
                this.pAY_NOField = value;
            }
        }
        
        /// <remarks/>
        public string OP_STATUS {
            get {
                return this.oP_STATUSField;
            }
            set {
                this.oP_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustomerListCompletedEventHandler(object sender, getCustomerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getItemListCompletedEventHandler(object sender, getItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCenterListCompletedEventHandler(object sender, getCenterListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCenterListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCenterListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getPuchaseServicesListCompletedEventHandler(object sender, getPuchaseServicesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPuchaseServicesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPuchaseServicesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCurrencyRatesCompletedEventHandler(object sender, getCurrencyRatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCurrencyRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCurrencyRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void loginTestCompletedEventHandler(object sender, loginTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void createPurchaseOrderInLogoCompletedEventHandler(object sender, createPurchaseOrderInLogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createPurchaseOrderInLogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createPurchaseOrderInLogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591